---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request: null

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test --workspaces --if-present

  pr-title:
    name: PR Title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      pull-requests: read

    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  megalinter:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/javascript@55a59b24a441e0e1943080d4a512d827710d4a9d # v9.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive MegaLinter reports
        if: success() || failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
