import { Developer, Ticket, Project, ProjectDoc, DashboardStats } from './types';

export const developers: Developer[] = [
  {
    id: 'zerwiz',
    githubUsername: 'zerwiz',
    displayName: 'Josef (Zerwiz)',
    role: 'CTO',
    avatarUrl: '',
    projects: ['wayofmono', 'wow', 'opticat'],
    isActive: true,
  },
  {
    id: 'craig',
    githubUsername: 'craig',
    displayName: 'Craig',
    role: 'Lead',
    avatarUrl: '',
    projects: ['wayofmono', 'wow'],
    isActive: true,
  },
  {
    id: 'andre',
    githubUsername: 'andre',
    displayName: 'Andre',
    role: 'Developer',
    avatarUrl: '',
    projects: ['wow', 'opticat'],
    isActive: true,
  },
  {
    id: 'tomas',
    githubUsername: 'tomas',
    displayName: 'Tomas',
    role: 'Developer',
    avatarUrl: '',
    projects: ['opticat'],
    isActive: true,
  },
];

export const tickets: Ticket[] = [
  {
    id: 'WOMONO-030',
    title: 'CTO Dashboard UI, Developer Portal & f-rr-d Telegram Agent',
    type: 'Feature',
    priority: 'High',
    status: 'In Progress',
    assignee: 'zerwiz',
    reporter: 'zerwiz',
    project: 'wayofmono',
    namespace: 'womono',
    category: 'frontend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: 'https://github.com/wayofmono/wo-web-ui/pull/42',
    githubIssue: 'https://github.com/wayofmono/wo-web-ui/issues/30',
    created: '2026-06-10',
    updated: '2026-06-10',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Build a web-based dashboard/portal with CTO view and developer view for visualizing workflow, tracking tickets, and managing work.',
    personalBreakdown: [
      'Set up dark theme with custom color palette',
      'Build mock data layer for tickets and developers',
      'Implement login/auth page with GitHub username',
      'Build sidebar navigation and layout shell',
      'Build CTO Dashboard overview with stats and project health',
      'Build Tickets view with advanced filtering',
      'Build Developer workflow view with Kanban board',
      'Build Review Queue with approve/request-changes actions',
      'Build Personal Developer view with TODO breakdown',
      'Build Docs browser view',
    ],
    linkedDocs: ['arch-dashboard-overview', 'adr-dashboard-tech-stack'],
  },
  {
    id: 'WOMONO-029',
    title: 'Implement OAuth2 flow for third-party integrations',
    type: 'Feature',
    priority: 'High',
    status: 'In Review',
    assignee: 'craig',
    reporter: 'zerwiz',
    project: 'wayofmono',
    namespace: 'womono',
    category: 'backend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: 'https://github.com/wayofmono/wo-core/pull/38',
    githubIssue: 'https://github.com/wayofmono/wo-core/issues/29',
    created: '2026-06-08',
    updated: '2026-06-10',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Add secure OAuth2 authorization code flow with PKCE support for connecting external services to the platform.',
    personalBreakdown: [
      'Research OAuth2 PKCE flow requirements',
      'Implement token endpoint handler',
      'Add authorization middleware',
      'Write integration tests',
    ],
    linkedDocs: ['arch-auth-flow'],
  },
  {
    id: 'WOMONO-028',
    title: 'Add WebSocket real-time notifications system',
    type: 'Feature',
    priority: 'Medium',
    status: 'Done',
    assignee: 'craig',
    reporter: 'craig',
    project: 'wayofmono',
    namespace: 'womono',
    category: 'backend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: 'https://github.com/wayofmono/wo-core/pull/35',
    githubIssue: '',
    created: '2026-06-01',
    updated: '2026-06-09',
    reviewedBy: 'zerwiz',
    reviewedAt: '2026-06-09',
    reviewStatus: 'Approved',
    reviewComments: 'LGTM, merged.',
    description: 'Implement WebSocket-based notification system for real-time updates across the platform.',
    personalBreakdown: [],
    linkedDocs: [],
  },
  {
    id: 'WOMONO-027',
    title: 'Fix memory leak in event processing pipeline',
    type: 'Bug',
    priority: 'Critical',
    status: 'Blocked',
    assignee: 'craig',
    reporter: 'andre',
    project: 'wayofmono',
    namespace: 'womono',
    category: 'backend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: 'https://github.com/wayofmono/wo-core/issues/27',
    created: '2026-06-05',
    updated: '2026-06-10',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Memory usage grows unbounded when processing high-volume event streams. Need to investigate and fix the cleanup logic in the event processor.',
    personalBreakdown: [
      'Profile memory usage under load',
      'Identify uncleaned references in event pipeline',
      'Implement proper cleanup/subscription disposal',
      'Add memory usage monitoring',
    ],
    linkedDocs: ['arch-event-pipeline'],
  },
  {
    id: 'WOW-015',
    title: 'Design and implement game lobby UI',
    type: 'Feature',
    priority: 'High',
    status: 'In Progress',
    assignee: 'andre',
    reporter: 'zerwiz',
    project: 'wow',
    namespace: 'wow',
    category: 'frontend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: 'https://github.com/wayofmono/wow/issues/15',
    created: '2026-06-07',
    updated: '2026-06-10',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Create an immersive game lobby interface with room browser, player avatars, chat, and ready-up mechanics.',
    personalBreakdown: [
      'Design lobby layout and component hierarchy',
      'Build room browser with filtering',
      'Implement player list with status indicators',
      'Add lobby chat component',
      'Create ready-up button and countdown timer',
    ],
    linkedDocs: ['guide-lobby-design'],
  },
  {
    id: 'WOW-014',
    title: 'Implement matchmaking algorithm for ranked play',
    type: 'Feature',
    priority: 'High',
    status: 'Backlog',
    assignee: 'andre',
    reporter: 'craig',
    project: 'wow',
    namespace: 'wow',
    category: 'backend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: 'https://github.com/wayofmono/wow/issues/14',
    created: '2026-06-06',
    updated: '2026-06-06',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Build an ELO-based matchmaking system with skill-based team balancing and queue management.',
    personalBreakdown: [
      'Define ELO calculation model',
      'Build matchmaking queue service',
      'Implement team balancing algorithm',
      'Add match history tracking',
    ],
    linkedDocs: [],
  },
  {
    id: 'WOW-013',
    title: 'Set up game server infrastructure with Docker',
    type: 'Task',
    priority: 'Medium',
    status: 'Done',
    assignee: 'andre',
    reporter: 'andre',
    project: 'wow',
    namespace: 'wow',
    category: 'devops',
    parentTicket: '',
    sharedTickets: [],
    prUrl: 'https://github.com/wayofmono/wow-infra/pull/12',
    githubIssue: '',
    created: '2026-05-28',
    updated: '2026-06-05',
    reviewedBy: 'craig',
    reviewedAt: '2026-06-05',
    reviewStatus: 'Approved',
    reviewComments: 'Infrastructure looks solid.',
    description: 'Dockerize game servers with compose orchestration and health checks.',
    personalBreakdown: [],
    linkedDocs: ['arch-game-infra'],
  },
  {
    id: 'WOW-012',
    title: 'Fix race condition in player disconnect handler',
    type: 'Bug',
    priority: 'Critical',
    status: 'In Review',
    assignee: 'andre',
    reporter: 'tomas',
    project: 'wow',
    namespace: 'wow',
    category: 'backend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: 'https://github.com/wayofmono/wow-server/pull/11',
    githubIssue: 'https://github.com/wayofmono/wow-server/issues/12',
    created: '2026-06-09',
    updated: '2026-06-10',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Players sometimes remain in-game state after disconnecting, causing ghost entities and state corruption.',
    personalBreakdown: [],
    linkedDocs: [],
  },
  {
    id: 'OPT-008',
    title: 'Build computer vision pipeline for product detection',
    type: 'Feature',
    priority: 'High',
    status: 'In Progress',
    assignee: 'tomas',
    reporter: 'zerwiz',
    project: 'opticat',
    namespace: 'opticat',
    category: 'ml',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: 'https://github.com/wayofmono/opticat/issues/8',
    created: '2026-06-03',
    updated: '2026-06-10',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Implement a multi-stage CV pipeline for detecting and classifying products in retail shelf images.',
    personalBreakdown: [
      'Research and select object detection model',
      'Build image preprocessing pipeline',
      'Implement model training pipeline',
      'Create inference service endpoint',
      'Add evaluation metrics dashboard',
    ],
    linkedDocs: ['arch-cv-pipeline', 'adr-model-selection'],
  },
  {
    id: 'OPT-007',
    title: 'Design REST API schema for product catalog',
    type: 'Feature',
    priority: 'Medium',
    status: 'In Review',
    assignee: 'tomas',
    reporter: 'tomas',
    project: 'opticat',
    namespace: 'opticat',
    category: 'backend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: 'https://github.com/wayofmono/opticat-api/pull/7',
    githubIssue: '',
    created: '2026-06-02',
    updated: '2026-06-09',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Design comprehensive REST API for product catalog management with filtering, pagination, and search.',
    personalBreakdown: [],
    linkedDocs: ['arch-api-design'],
  },
  {
    id: 'OPT-006',
    title: 'Set up ML model versioning and registry',
    type: 'Task',
    priority: 'Medium',
    status: 'Backlog',
    assignee: 'tomas',
    reporter: 'zerwiz',
    project: 'opticat',
    namespace: 'opticat',
    category: 'ml',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: 'https://github.com/wayofmono/opticat/issues/6',
    created: '2026-06-01',
    updated: '2026-06-01',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Implement model versioning with MLflow or similar tool for tracking experiments and deployments.',
    personalBreakdown: [
      'Evaluate MLflow vs DVC for model registry',
      'Set up model storage backend',
      'Create versioning CLI tool',
      'Document model publishing workflow',
    ],
    linkedDocs: [],
  },
  {
    id: 'WOMONO-026',
    title: 'Research: Evaluate monorepo tooling (Nx vs Turborepo)',
    type: 'Research',
    priority: 'Low',
    status: 'Done',
    assignee: 'zerwiz',
    reporter: 'zerwiz',
    project: 'wayofmono',
    namespace: 'womono',
    category: 'research',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: '',
    created: '2026-05-25',
    updated: '2026-06-02',
    reviewedBy: 'craig',
    reviewedAt: '2026-06-02',
    reviewStatus: 'Approved',
    reviewComments: 'Good analysis. Let\'s go with Turborepo.',
    description: 'Compare Nx and Turborepo for monorepo management. Evaluate build times, caching, DX, and ecosystem support.',
    personalBreakdown: [],
    linkedDocs: ['adr-monorepo-tooling'],
  },
  {
    id: 'WOMONO-025',
    title: 'Refactor: Migrate to shared utility library',
    type: 'Refactor',
    priority: 'Medium',
    status: 'Backlog',
    assignee: 'craig',
    reporter: 'zerwiz',
    project: 'wayofmono',
    namespace: 'womono',
    category: 'refactor',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: '',
    created: '2026-06-04',
    updated: '2026-06-04',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Extract duplicated utility functions across projects into a shared @wayofmono/utils package.',
    personalBreakdown: [
      'Audit existing utility code across projects',
      'Design shared package API surface',
      'Create @wayofmono/utils package',
      'Migrate consumers one project at a time',
    ],
    linkedDocs: [],
  },
  {
    id: 'WOMONO-024',
    title: 'Write API documentation for developer portal',
    type: 'Docs',
    priority: 'Low',
    status: 'Backlog',
    assignee: 'craig',
    reporter: 'craig',
    project: 'wayofmono',
    namespace: 'womono',
    category: 'docs',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: '',
    created: '2026-06-03',
    updated: '2026-06-03',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Create comprehensive API docs using OpenAPI spec for all public endpoints.',
    personalBreakdown: [],
    linkedDocs: [],
  },
  {
    id: 'WOW-011',
    title: 'Implement in-game chat with profanity filter',
    type: 'Feature',
    priority: 'Medium',
    status: 'Backlog',
    assignee: 'craig',
    reporter: 'andre',
    project: 'wow',
    namespace: 'wow',
    category: 'frontend',
    parentTicket: '',
    sharedTickets: [],
    prUrl: '',
    githubIssue: '',
    created: '2026-06-08',
    updated: '2026-06-08',
    reviewedBy: '',
    reviewedAt: '',
    reviewStatus: 'Pending',
    reviewComments: '',
    description: 'Build real-time in-game chat system with message filtering, emoji support, and moderation tools.',
    personalBreakdown: [
      'Design chat UI component',
      'Implement WebSocket message handler',
      'Add profanity filter service',
      'Create moderation panel for admins',
    ],
    linkedDocs: [],
  },
];

export const projects: Project[] = [
  {
    slug: 'wayofmono',
    name: 'WayOfMono',
    description: 'Core platform — engineering harness, CI/CD, developer tooling',
    velocity: 8,
    openTickets: 7,
    closedThisWeek: 3,
    blockers: 1,
    upcomingMilestones: ['v0.3.0 - Dashboard Launch', 'v0.4.0 - Telegram Agent'],
  },
  {
    slug: 'wow',
    name: 'WoW',
    description: 'Game platform — multiplayer game server, lobby, matchmaking',
    velocity: 5,
    openTickets: 5,
    closedThisWeek: 1,
    blockers: 1,
    upcomingMilestones: ['Alpha Build', 'Matchmaking Beta'],
  },
  {
    slug: 'opticat',
    name: 'OptiCat',
    description: 'Computer vision — product detection, retail analytics pipeline',
    velocity: 3,
    openTickets: 3,
    closedThisWeek: 0,
    blockers: 0,
    upcomingMilestones: ['MVP Demo', 'API Release'],
  },
];

export const docs: ProjectDoc[] = [
  {
    id: 'arch-dashboard-overview',
    title: 'Dashboard Architecture Overview',
    type: 'architecture',
    project: 'wayofmono',
    path: 'wayofmono/docs/architecture/dashboard-overview.md',
    updated: '2026-06-10',
    author: 'zerwiz',
    summary: 'High-level architecture of the CTO Dashboard web UI, including data flow from f-rr-d markdown files to React components.',
  },
  {
    id: 'adr-dashboard-tech-stack',
    title: 'ADR-003: Dashboard Technology Stack',
    type: 'decision',
    project: 'wayofmono',
    path: 'wayofmono/docs/decisions/adr-003-dashboard-tech-stack.md',
    updated: '2026-06-09',
    author: 'zerwiz',
    summary: 'Decision to use Next.js + shadcn/ui for the dashboard, reading directly from f-rr-d markdown files.',
  },
  {
    id: 'arch-auth-flow',
    title: 'OAuth2 Authorization Flow',
    type: 'architecture',
    project: 'wayofmono',
    path: 'wayofmono/docs/architecture/auth-flow.md',
    updated: '2026-06-08',
    author: 'craig',
    summary: 'Detailed OAuth2 PKCE flow diagram and implementation notes for third-party integrations.',
  },
  {
    id: 'arch-event-pipeline',
    title: 'Event Processing Pipeline Architecture',
    type: 'architecture',
    project: 'wayofmono',
    path: 'wayofmono/docs/architecture/event-pipeline.md',
    updated: '2026-06-05',
    author: 'craig',
    summary: 'Architecture of the event processing system including memory management and cleanup strategies.',
  },
  {
    id: 'adr-monorepo-tooling',
    title: 'ADR-002: Monorepo Tooling Decision',
    type: 'decision',
    project: 'wayofmono',
    path: 'wayofmono/docs/decisions/adr-002-monorepo-tooling.md',
    updated: '2026-06-02',
    author: 'zerwiz',
    summary: 'Comparison of Nx vs Turborepo with decision to adopt Turborepo for the monorepo setup.',
  },
  {
    id: 'guide-lobby-design',
    title: 'Game Lobby Design Guide',
    type: 'guide',
    project: 'wow',
    path: 'wow/docs/guides/lobby-design.md',
    updated: '2026-06-07',
    author: 'andre',
    summary: 'Design specifications and UX guidelines for the game lobby interface.',
  },
  {
    id: 'arch-game-infra',
    title: 'Game Server Infrastructure',
    type: 'architecture',
    project: 'wow',
    path: 'wow/docs/architecture/game-infra.md',
    updated: '2026-06-04',
    author: 'andre',
    summary: 'Docker-based game server infrastructure with orchestration details.',
  },
  {
    id: 'arch-cv-pipeline',
    title: 'Computer Vision Pipeline Architecture',
    type: 'architecture',
    project: 'opticat',
    path: 'opticat/docs/architecture/cv-pipeline.md',
    updated: '2026-06-03',
    author: 'tomas',
    summary: 'Multi-stage CV pipeline for product detection in retail shelf images.',
  },
  {
    id: 'adr-model-selection',
    title: 'ADR-001: Object Detection Model Selection',
    type: 'decision',
    project: 'opticat',
    path: 'opticat/docs/decisions/adr-001-model-selection.md',
    updated: '2026-06-03',
    author: 'tomas',
    summary: 'Evaluation and selection of YOLOv8 for product detection use case.',
  },
  {
    id: 'arch-api-design',
    title: 'REST API Design Specification',
    type: 'architecture',
    project: 'opticat',
    path: 'opticat/docs/architecture/api-design.md',
    updated: '2026-06-02',
    author: 'tomas',
    summary: 'REST API schema design for product catalog management.',
  },
];

export function getDashboardStats(): DashboardStats {
  return {
    totalTickets: tickets.length,
    inProgress: tickets.filter(t => t.status === 'In Progress').length,
    inReview: tickets.filter(t => t.status === 'In Review').length,
    blocked: tickets.filter(t => t.status === 'Blocked').length,
    doneThisWeek: tickets.filter(t => {
      if (t.status !== 'Done') return false;
      const updated = new Date(t.updated);
      const weekAgo = new Date('2026-06-03');
      return updated >= weekAgo;
    }).length,
    reviewQueue: tickets.filter(t => t.status === 'In Review' && t.reviewStatus === 'Pending').length,
  };
}

export function getDeveloperTickets(developerId: string): Ticket[] {
  return tickets.filter(t => t.assignee === developerId);
}

export function getReviewQueue(): Ticket[] {
  return tickets.filter(t => t.status === 'In Review' && t.reviewStatus === 'Pending');
}

export function getProjectTickets(project: string): Ticket[] {
  return tickets.filter(t => t.project === project);
}

export function getTicketsByStatus(status: string): Ticket[] {
  if (status === 'all') return tickets;
  return tickets.filter(t => t.status === status);
}