---
VALIDATE_ALL_CODEBASE: false

ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - ENV_DOTENV_LINTER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_GITLEAKS
  - SPELL_CODESPELL
  - TYPESCRIPT_ES
  - YAML_PRETTIER
  - YAML_YAMLLINT

FILTER_REGEX_EXCLUDE: (.*CHANGELOG\.md|\.gitignore|\.mega-linter\.yml)
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
SARIF_REPORTER: false
FLAVOR_SUGGESTIONS: false
REPORTERS_MARKDOWN_TYPE: simple
